"""Synthetic transcripts with the shape of real Claude Code and Codex files.

Every word is fictional. Standard library only, so the capture tests can run on
Python 3.9 without third-party packages.
"""
import json
from pathlib import Path
import sys
import tempfile

SCRIPTS = Path(__file__).resolve().parents[1]
PLUGIN = Path(__file__).resolve().parents[4]
sys.path.insert(0, str(SCRIPTS))


def stamp(minute):
    return '2026-10-06T14:%02d:%02d.123Z' % (minute // 60 % 60, minute % 60)


class Claude:
    """Rows as Claude Code writes them, including harness rows that are not chat."""

    def __init__(self, session_id, cwd, entrypoint='cli'):
        self.sid, self.cwd, self.entrypoint, self.rows, self.n = session_id, str(cwd), entrypoint, [], 0

    def row(self, kind, content, **extra):
        self.n += 1
        base = {'parentUuid': 'r%d' % (self.n - 1) if self.n > 1 else None, 'isSidechain': False,
                'userType': 'external', 'cwd': self.cwd, 'sessionId': self.sid, 'version': '2.1.0',
                'gitBranch': 'main', 'entrypoint': self.entrypoint, 'type': kind,
                'message': {'role': kind, 'content': content}, 'uuid': 'r%d' % self.n,
                'timestamp': stamp(self.n)}
        base.update(extra)
        self.rows.append(base)
        return self

    def user(self, text, **extra):
        return self.row('user', text, **extra)

    def assistant(self, text, tools=()):
        content = [{'type': 'text', 'text': text}] + [{'type': 'tool_use', 'id': 't', 'name': t, 'input': {}} for t in tools]
        return self.row('assistant', content)

    def tool_result(self):
        return self.row('user', [{'type': 'tool_result', 'tool_use_id': 't', 'content': 'ok'}])

    def harness(self):
        self.row('user', 'Caveat: The messages below were generated by the user while running local commands.', isMeta=True)
        self.user('<command-name>/ck-help</command-name>\n<command-message>ck-help</command-message>\n<command-args></command-args>')
        self.user('<local-command-stdout>Fictional output</local-command-stdout>')
        return self

    def title(self, kind, text):
        key = {'custom-title': 'customTitle', 'summary': 'summary', 'ai-title': 'aiTitle'}[kind]
        self.rows.append({'type': kind, key: text, 'sessionId': self.sid})
        return self

    def move(self, cwd):
        self.cwd = str(cwd)
        return self

    def bytes(self):
        return ''.join(json.dumps(r) + '\n' for r in self.rows).encode()

    def save(self, folder):
        path = Path(folder)/(self.sid + '.jsonl')
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(self.bytes())
        return path


class Codex:
    def __init__(self, session_id, cwd, originator='codex_cli_rs'):
        self.sid = session_id
        self.rows = [{'timestamp': stamp(0), 'type': 'session_meta',
                      'payload': {'id': session_id, 'timestamp': stamp(0), 'cwd': str(cwd),
                                  'originator': originator, 'cli_version': '0.1.0'}}]
        self.n = 0

    def item(self, payload):
        self.n += 1
        self.rows.append({'timestamp': stamp(self.n), 'type': 'response_item', 'payload': payload})
        return self

    def message(self, role, text):
        kind = 'input_text' if role in ('user', 'developer') else 'output_text'
        return self.item({'type': 'message', 'role': role, 'content': [{'type': kind, 'text': text}]})

    def harness(self):
        self.message('developer', 'Fictional developer instructions')
        self.message('user', '<environment_context>\n  <cwd>/fictional</cwd>\n</environment_context>')
        return self.message('user', '# AGENTS.md instructions for /fictional\n\nBe brief.')

    def tool(self, name='shell'):
        return self.item({'type': 'function_call', 'name': name, 'arguments': '{}', 'call_id': 'c%d' % self.n})

    def turn(self, cwd):
        self.rows.append({'timestamp': stamp(self.n), 'type': 'turn_context', 'payload': {'cwd': str(cwd)}})
        return self

    def save(self, folder):
        path = Path(folder)/'2026/10/06'/('rollout-2026-10-06T14-00-00-' + self.sid + '.jsonl')
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(''.join(json.dumps(r) + '\n' for r in self.rows).encode())
        return path


class Machine:
    """A temporary Mac: home folder, transcript folders, projects, vault and state."""

    def __init__(self, machine='mac-mini', enabled=True):
        self.tmp = tempfile.TemporaryDirectory()
        self.root = Path(self.tmp.name).resolve()
        self.home = self.root/'home'
        self.claude = self.home/'.claude/projects'
        self.codex = self.home/'.codex/sessions'
        self.projects = self.root/'projects'
        self.vault = self.root/'Vault'
        self.state = self.root/'private-state'
        for folder in (self.claude, self.codex, self.projects/'garden/beds', self.projects/'orchard', self.vault):
            folder.mkdir(parents=True)
        self.cfg = {'schema': 1, 'machine': machine, 'role': 'hub', 'vault': str(self.vault),
                    'state': str(self.state), 'accounts': {'claude': 'personal', 'openai': 'personal'},
                    'capture': {'enabled': enabled, 'hosts': ['claude-code', 'codex'],
                                'roots': [str(self.projects)], 'exclude': [], 'idle_minutes': 10,
                                'default_remote_device': None,
                                'transcript_roots': {'claude-code': [str(self.claude)], 'codex': [str(self.codex)]}}}

    def config_file(self):
        path = self.home/'.config/connected-knowledge/config.json'
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(self.cfg))
        return path

    def env(self, **extra):
        import os
        env = {'PATH': os.environ.get('PATH', '/usr/bin:/bin'), 'HOME': str(self.home)}
        env.update(extra)
        return env

    def vault_files(self):
        return sorted(p.relative_to(self.vault).as_posix() for p in self.vault.rglob('*') if p.is_file())

    def cleanup(self):
        self.tmp.cleanup()
