"""Read Claude Code and Codex session transcripts (standard library only).

Transcript formats are observed local storage, not a stable vendor interface.
Unknown rows are skipped and counted; the raw copy keeps everything.
"""
from datetime import datetime, timezone
import json
from pathlib import Path
import re

from ck_config import inside, transcript_roots

MAX_TRANSCRIPT = 256 * 1024 * 1024
PLATFORMS = {'claude-code': 'Claude Code', 'codex': 'Codex'}
# Text the host or harness inserts into a user turn; never shown as "You said".
WRAPPER_PREFIXES = (
    '<local-command-stdout>', '<local-command-stderr>', '<bash-input>', '<bash-stdout>',
    '<bash-stderr>', '<user-prompt-submit-hook>', '<environment_context>', '<user_instructions>',
    '<permissions instructions>', '# AGENTS.md instructions', '<INSTRUCTIONS>',
    'Caveat: The messages below were generated by the user while running local commands',
    '[Request interrupted by user',
)
REMINDER = re.compile(r'<system-reminder>.*?</system-reminder>', re.S)
COMMAND = re.compile(r'<command-name>(.*?)</command-name>', re.S)
COMMAND_ARGS = re.compile(r'<command-args>(.*?)</command-args>', re.S)
TITLE_ROWS = {'custom-title': 'custom', 'ai-title': 'host', 'summary': 'host'}
TITLE_KEYS = ('customTitle', 'aiTitle', 'title', 'summary')


def iso(value):
    """ISO 8601 with offset, in local time; epoch seconds and 'Z' accepted."""
    if value is None or value == '':
        return None
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        moment = datetime.fromtimestamp(value, timezone.utc)
    elif isinstance(value, str):
        match = re.match(r'^(\d{4}-\d\d-\d\d)[T ](\d\d:\d\d(?::\d\d)?)(?:\.(\d+))?(Z|[+-]\d\d:?\d\d)?$', value.strip())
        if not match:
            return None
        day, clock, fraction, zone = match.groups()
        if len(clock) == 5:
            clock += ':00'
        zone = '+00:00' if zone in (None, 'Z') else (zone if ':' in zone else zone[:3] + ':' + zone[3:])
        micro = (fraction or '0')[:6].ljust(6, '0')
        moment = datetime.fromisoformat(day + 'T' + clock + '.' + micro + zone)
    else:
        return None
    return moment.astimezone().replace(microsecond=0).isoformat()


def safe_transcript(path, cfg, host):
    path = Path(path).expanduser()
    if not path.is_absolute():
        raise ValueError('Transcript path must be absolute')
    if any(p.is_symlink() for p in (path, *path.parents)):
        raise ValueError('Symlinked transcripts are not read')
    if path.suffix != '.jsonl' or not path.is_file():
        raise ValueError('Expected a local .jsonl transcript')
    if not any(inside(path, root) for root in transcript_roots(cfg, host)):
        raise ValueError('Transcript is outside the transcript folders for ' + host)
    if path.stat().st_size > MAX_TRANSCRIPT:
        raise ValueError('Transcript is larger than the 256 MB capture limit')
    return path.resolve()


def text_blocks(content, counts):
    """Plain text of a message; tool, image and thinking blocks are counted, not shown."""
    if isinstance(content, str):
        return [content], []
    if not isinstance(content, list):
        counts['unknown'] += 1
        return [], []
    texts, tools = [], []
    for block in content:
        if not isinstance(block, dict):
            continue
        kind = block.get('type')
        if kind in ('text', 'input_text', 'output_text') and isinstance(block.get('text'), str):
            texts.append(block['text'])
        elif kind == 'tool_use':
            tools.append(str(block.get('name') or 'tool'))
        elif kind == 'tool_result':
            counts['tool'] += 1
        else:
            counts['other'] += 1
    return texts, tools


def clean_user_text(text, counts):
    """Separate what the person typed from what the harness inserted."""
    command = COMMAND.search(text)
    if command:
        args = COMMAND_ARGS.search(text)
        name = command.group(1).strip()
        return 'command', (name + (' ' + args.group(1).strip() if args and args.group(1).strip() else ''))
    stripped = REMINDER.sub('', text).strip()
    if stripped != text.strip():
        counts['wrapper'] += 1
    if not stripped or stripped.startswith(WRAPPER_PREFIXES):
        if stripped:
            counts['wrapper'] += 1
        return None, None
    return 'user', stripped


def parse(raw, host, name=''):
    """Normalize one transcript. ``name`` is the file stem, used for identity."""
    counts = {'meta': 0, 'wrapper': 0, 'tool': 0, 'sidechain': 0, 'other': 0, 'unknown': 0}
    messages, directories, session_ids, titles = [], [], [], {}
    created = updated = surface = None
    pending_tools = []
    lines = raw.decode('utf-8').split('\n')
    # A partly written final line is normal while a session is running.
    if lines and lines[-1].strip():
        try:
            json.loads(lines[-1])
        except ValueError:
            lines = lines[:-1]
    for number, line in enumerate(lines, 1):
        if not line.strip():
            continue
        try:
            row = json.loads(line)
        except ValueError:
            raise ValueError('Transcript line ' + str(number) + ' is not valid JSON')
        if not isinstance(row, dict):
            counts['unknown'] += 1
            continue
        stamp = iso(row.get('timestamp'))
        if host == 'claude-code':
            kind = row.get('type')
            if kind in TITLE_ROWS:
                value = next((row[k] for k in TITLE_KEYS if isinstance(row.get(k), str) and row[k].strip()), None)
                if value:
                    titles[TITLE_ROWS[kind]] = value.strip()
                continue
            if row.get('sessionId') and row['sessionId'] not in session_ids:
                session_ids.append(row['sessionId'])
            if row.get('cwd') and row['cwd'] not in directories:
                directories.append(row['cwd'])
            if row.get('entrypoint') and not surface:
                surface = row['entrypoint']
            if kind not in ('user', 'assistant'):
                continue
            if row.get('isSidechain'):
                counts['sidechain'] += 1
                continue
            if row.get('isMeta'):
                counts['meta'] += 1
                continue
            data = row.get('message') if isinstance(row.get('message'), dict) else {}
            mid = row.get('uuid') or 'line-' + str(number)
            texts, tools = text_blocks(data.get('content'), counts)
            role = data.get('role', kind)
        elif host == 'codex':
            data = row.get('payload') if isinstance(row.get('payload'), dict) else {}
            kind = row.get('type')
            if kind == 'session_meta':
                sid = data.get('id') or data.get('session_id')
                if sid and sid not in session_ids:
                    session_ids.append(sid)
                surface = surface or data.get('originator')
                stamp = stamp or iso(data.get('timestamp'))
            if kind in ('session_meta', 'turn_context') and data.get('cwd') and data['cwd'] not in directories:
                directories.append(data['cwd'])
            if kind != 'response_item':
                continue
            if data.get('type') in ('function_call', 'custom_tool_call', 'local_shell_call'):
                pending_tools.append(str(data.get('name') or 'shell'))
                continue
            if data.get('type') != 'message' or data.get('role') not in ('user', 'assistant'):
                if data.get('type') == 'message':
                    counts['meta'] += 1
                continue
            mid = data.get('id') or 'line-' + str(number)
            texts, tools = text_blocks(data.get('content'), counts)
            role = data['role']
        else:
            raise ValueError('Unsupported host: ' + host)
        if stamp:
            created = created or stamp
            updated = stamp
        text = '\n\n'.join(t for t in texts if t.strip())
        if role == 'user':
            role, text = clean_user_text(text, counts) if text else (None, None)
            if role is None:
                continue
        elif role == 'assistant':
            tools = pending_tools + tools
            pending_tools = []
            if not text.strip() and not tools:
                continue
        else:
            counts['other'] += 1
            continue
        message = {'id': str(mid), 'role': role, 'text': text or '', 'time': stamp}
        if role == 'assistant' and tools:
            message['tools'] = tools
        # Claude Code writes one row per content block; merge them into one turn.
        if messages and role == 'assistant' and messages[-1]['role'] == 'assistant' and host == 'claude-code':
            previous = messages[-1]
            previous['text'] = '\n\n'.join(t for t in (previous['text'], message['text']) if t)
            previous['tools'] = previous.get('tools', []) + message.get('tools', [])
            previous.setdefault('parts', [previous['id']]).append(message['id'])
            continue
        messages.append(message)
    if not session_ids:
        raise ValueError('Transcript has no session identity')
    # A resumed Claude Code session can carry earlier session IDs; the file name wins.
    native = session_ids[0] if host == 'codex' else (name if name in session_ids else session_ids[-1])
    if not any(m['role'] == 'user' for m in messages):
        raise ValueError('Transcript has no user message yet')
    return {'host': host, 'platform': PLATFORMS[host], 'native_id': native, 'session_ids': session_ids,
            'messages': messages, 'directories': directories, 'created': created, 'updated': updated,
            'titles': titles, 'surface_hint': surface, 'skipped': counts,
            'coverage': 'full_export'}


def surface(host, hint, queued=None):
    """cli, desktop, ide or remote-control, from what the transcript or hook saw."""
    if queued:
        return queued
    hint = (hint or '').lower()
    if 'remote' in hint:
        return 'remote-control'
    if 'desktop' in hint or 'work' in hint:
        return 'desktop'
    if any(k in hint for k in ('vscode', 'jetbrains', 'ide', 'cursor')):
        return 'ide'
    return 'cli' if hint or host in PLATFORMS else None


# --------------------------------------------------------------- discovery

def all_transcripts(cfg, host):
    found = []
    for root in transcript_roots(cfg, host):
        if not root.is_dir():
            continue
        for path in root.rglob('*.jsonl'):
            if 'subagents' in path.parts or path.is_symlink() or not path.is_file():
                continue
            found.append(path)
    return sorted(found, key=lambda p: p.stat().st_mtime, reverse=True)


def first_directory(path, limit=256 * 1024):
    """The first working folder recorded in a transcript, reading only its start."""
    with open(str(path), 'rb') as stream:
        head = stream.read(limit)
    for line in head.split(b'\n'):
        try:
            row = json.loads(line)
        except ValueError:
            continue
        if not isinstance(row, dict):
            continue
        payload = row.get('payload') if isinstance(row.get('payload'), dict) else {}
        directory = row.get('cwd') or payload.get('cwd')
        if isinstance(directory, str) and directory:
            return directory
    return None


def find(cfg, host, session_id=None, directory=None):
    """Locate a transcript by session ID, or the newest one for a working folder."""
    for path in all_transcripts(cfg, host):
        if session_id:
            if path.stem == session_id or path.stem.endswith(session_id):
                return path
            continue
        if directory is None:
            return path
        start = first_directory(path)
        if start and inside(start, directory):
            return path
    return None
